### PR TITLE
Pre-release for the null safety migration of this package.

### PR DESCRIPTION
**Pull request by ilap**
Hi,

I migrated this package to the null safety and therefor would be nice if you could update the package in `pub.dev`.

Thx in advance for your help.

Cheers,

Pal

### CODE REVIEW

**Comment by acoutts** [comment]
@stevenroose @hitecherik any update to get this merged / published? Downstream packages need this package migrated so they can migrate.

**Comment by hitecherik** [comment]
Hey -- I'm not a maintainer, so I think only @stevenroose can help :)

**Comment by pheki** [comment]
Notice that now dart 2.12 has officially been released, so it could just be `version: 0.2.0` and `test: ^1.16.5`

**Comment by stevenroose** [comment]
If it doesn't need to be a pre-release, feel free to update this to 0.2.0 and I can merge it and release it :)

**Pull request merged**
